# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/background/main_information.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import protos.base.item_detail_infomation_pb2
import protos.base.dbo_settings_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='protos/background/main_information.proto',
  package='',
  serialized_pb=_b('\n(protos/background/main_information.proto\x1a(protos/base/item_detail_infomation.proto\x1a\x1eprotos/base/dbo_settings.proto\"w\n\x0fMainInformation\x12\x13\n\x0bRequestName\x18\x02 \x02(\t\x12\x11\n\tRequestId\x18\x03 \x02(\t\x12\x1a\n\x12RequestDescription\x18\x07 \x01(\t\x12 \n\x0b\x64\x62o_setting\x18\x08 \x01(\x0b\x32\x0b.DboSetting\"\xaa\x02\n\nItemStruct\x12\x17\n\x0fItemIsAvailable\x18\x01 \x02(\x08\x12\x0e\n\x06ItemID\x18\x02 \x01(\t\x12\x10\n\x08ItemName\x18\x03 \x02(\t\x12\x17\n\x0fItemchineseName\x18\x04 \x02(\t\x12\x18\n\x10ItemCategoryName\x18\x05 \x02(\t\x12\x17\n\x0fItemDescription\x18\x06 \x01(\t\x12\x12\n\nItemPicUrl\x18\x07 \x01(\t\x12?\n\x14subProductCollection\x18\x08 \x01(\x0b\x32!.ItemsDetailInformationCollection\x12\x16\n\x0eItemInHomePage\x18\t \x01(\x08\x12\x11\n\tIsHotItem\x18\n \x01(\x08\x12\x15\n\rHotItemPicUrl\x18\x0b \x01(\t\"\x1e\n\x0bOrderStruct\x12\x0f\n\x07orderID\x18\x02 \x02(\t\"*\n\x0cItemsRequest\x12\x1a\n\x05items\x18\x01 \x03(\x0b\x32\x0b.ItemStruct\"\x85\x03\n\x0cPostRequests\x12*\n\x07msgtype\x18\x01 \x02(\x0e\x32\x19.PostRequests.MessageType\x12\r\n\x05\x64\x62oid\x18\x02 \x02(\t\x12,\n\noperations\x18\x05 \x03(\x0b\x32\x18.PostRequests.Operations\x1a\x9a\x01\n\nOperations\x12,\n\x03req\x18\x01 \x02(\x0e\x32\x1f.PostRequests.RequestOperations\x12\x1a\n\x05items\x18\x02 \x03(\x0b\x32\x0b.ItemStruct\x12\x1c\n\x06orders\x18\x03 \x03(\x0b\x32\x0c.OrderStruct\x12$\n\nmain_infos\x18\x04 \x03(\x0b\x32\x10.MainInformation\"9\n\x0bMessageType\x12\x0c\n\x08MAININFO\x10\x00\x12\r\n\tITEMSINFO\x10\x01\x12\r\n\tORDERINFO\x10\x02\"4\n\x11RequestOperations\x12\x07\n\x03\x41\x44\x44\x10\x00\x12\n\n\x06MODIFY\x10\x01\x12\n\n\x06\x44\x45LETE\x10\x02')
  ,
  dependencies=[protos.base.item_detail_infomation_pb2.DESCRIPTOR,protos.base.dbo_settings_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_POSTREQUESTS_MESSAGETYPE = _descriptor.EnumDescriptor(
  name='MessageType',
  full_name='PostRequests.MessageType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='MAININFO', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ITEMSINFO', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ORDERINFO', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=895,
  serialized_end=952,
)
_sym_db.RegisterEnumDescriptor(_POSTREQUESTS_MESSAGETYPE)

_POSTREQUESTS_REQUESTOPERATIONS = _descriptor.EnumDescriptor(
  name='RequestOperations',
  full_name='PostRequests.RequestOperations',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ADD', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MODIFY', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DELETE', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=954,
  serialized_end=1006,
)
_sym_db.RegisterEnumDescriptor(_POSTREQUESTS_REQUESTOPERATIONS)


_MAININFORMATION = _descriptor.Descriptor(
  name='MainInformation',
  full_name='MainInformation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='RequestName', full_name='MainInformation.RequestName', index=0,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='RequestId', full_name='MainInformation.RequestId', index=1,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='RequestDescription', full_name='MainInformation.RequestDescription', index=2,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dbo_setting', full_name='MainInformation.dbo_setting', index=3,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=118,
  serialized_end=237,
)


_ITEMSTRUCT = _descriptor.Descriptor(
  name='ItemStruct',
  full_name='ItemStruct',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ItemIsAvailable', full_name='ItemStruct.ItemIsAvailable', index=0,
      number=1, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ItemID', full_name='ItemStruct.ItemID', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ItemName', full_name='ItemStruct.ItemName', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ItemchineseName', full_name='ItemStruct.ItemchineseName', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ItemCategoryName', full_name='ItemStruct.ItemCategoryName', index=4,
      number=5, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ItemDescription', full_name='ItemStruct.ItemDescription', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ItemPicUrl', full_name='ItemStruct.ItemPicUrl', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='subProductCollection', full_name='ItemStruct.subProductCollection', index=7,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ItemInHomePage', full_name='ItemStruct.ItemInHomePage', index=8,
      number=9, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='IsHotItem', full_name='ItemStruct.IsHotItem', index=9,
      number=10, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='HotItemPicUrl', full_name='ItemStruct.HotItemPicUrl', index=10,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=240,
  serialized_end=538,
)


_ORDERSTRUCT = _descriptor.Descriptor(
  name='OrderStruct',
  full_name='OrderStruct',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='orderID', full_name='OrderStruct.orderID', index=0,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=540,
  serialized_end=570,
)


_ITEMSREQUEST = _descriptor.Descriptor(
  name='ItemsRequest',
  full_name='ItemsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='items', full_name='ItemsRequest.items', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=572,
  serialized_end=614,
)


_POSTREQUESTS_OPERATIONS = _descriptor.Descriptor(
  name='Operations',
  full_name='PostRequests.Operations',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='req', full_name='PostRequests.Operations.req', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='items', full_name='PostRequests.Operations.items', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='orders', full_name='PostRequests.Operations.orders', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='main_infos', full_name='PostRequests.Operations.main_infos', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=739,
  serialized_end=893,
)

_POSTREQUESTS = _descriptor.Descriptor(
  name='PostRequests',
  full_name='PostRequests',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='msgtype', full_name='PostRequests.msgtype', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dboid', full_name='PostRequests.dboid', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='operations', full_name='PostRequests.operations', index=2,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_POSTREQUESTS_OPERATIONS, ],
  enum_types=[
    _POSTREQUESTS_MESSAGETYPE,
    _POSTREQUESTS_REQUESTOPERATIONS,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=617,
  serialized_end=1006,
)

_MAININFORMATION.fields_by_name['dbo_setting'].message_type = protos.base.dbo_settings_pb2._DBOSETTING
_ITEMSTRUCT.fields_by_name['subProductCollection'].message_type = protos.base.item_detail_infomation_pb2._ITEMSDETAILINFORMATIONCOLLECTION
_ITEMSREQUEST.fields_by_name['items'].message_type = _ITEMSTRUCT
_POSTREQUESTS_OPERATIONS.fields_by_name['req'].enum_type = _POSTREQUESTS_REQUESTOPERATIONS
_POSTREQUESTS_OPERATIONS.fields_by_name['items'].message_type = _ITEMSTRUCT
_POSTREQUESTS_OPERATIONS.fields_by_name['orders'].message_type = _ORDERSTRUCT
_POSTREQUESTS_OPERATIONS.fields_by_name['main_infos'].message_type = _MAININFORMATION
_POSTREQUESTS_OPERATIONS.containing_type = _POSTREQUESTS
_POSTREQUESTS.fields_by_name['msgtype'].enum_type = _POSTREQUESTS_MESSAGETYPE
_POSTREQUESTS.fields_by_name['operations'].message_type = _POSTREQUESTS_OPERATIONS
_POSTREQUESTS_MESSAGETYPE.containing_type = _POSTREQUESTS
_POSTREQUESTS_REQUESTOPERATIONS.containing_type = _POSTREQUESTS
DESCRIPTOR.message_types_by_name['MainInformation'] = _MAININFORMATION
DESCRIPTOR.message_types_by_name['ItemStruct'] = _ITEMSTRUCT
DESCRIPTOR.message_types_by_name['OrderStruct'] = _ORDERSTRUCT
DESCRIPTOR.message_types_by_name['ItemsRequest'] = _ITEMSREQUEST
DESCRIPTOR.message_types_by_name['PostRequests'] = _POSTREQUESTS

MainInformation = _reflection.GeneratedProtocolMessageType('MainInformation', (_message.Message,), dict(
  DESCRIPTOR = _MAININFORMATION,
  __module__ = 'protos.background.main_information_pb2'
  # @@protoc_insertion_point(class_scope:MainInformation)
  ))
_sym_db.RegisterMessage(MainInformation)

ItemStruct = _reflection.GeneratedProtocolMessageType('ItemStruct', (_message.Message,), dict(
  DESCRIPTOR = _ITEMSTRUCT,
  __module__ = 'protos.background.main_information_pb2'
  # @@protoc_insertion_point(class_scope:ItemStruct)
  ))
_sym_db.RegisterMessage(ItemStruct)

OrderStruct = _reflection.GeneratedProtocolMessageType('OrderStruct', (_message.Message,), dict(
  DESCRIPTOR = _ORDERSTRUCT,
  __module__ = 'protos.background.main_information_pb2'
  # @@protoc_insertion_point(class_scope:OrderStruct)
  ))
_sym_db.RegisterMessage(OrderStruct)

ItemsRequest = _reflection.GeneratedProtocolMessageType('ItemsRequest', (_message.Message,), dict(
  DESCRIPTOR = _ITEMSREQUEST,
  __module__ = 'protos.background.main_information_pb2'
  # @@protoc_insertion_point(class_scope:ItemsRequest)
  ))
_sym_db.RegisterMessage(ItemsRequest)

PostRequests = _reflection.GeneratedProtocolMessageType('PostRequests', (_message.Message,), dict(

  Operations = _reflection.GeneratedProtocolMessageType('Operations', (_message.Message,), dict(
    DESCRIPTOR = _POSTREQUESTS_OPERATIONS,
    __module__ = 'protos.background.main_information_pb2'
    # @@protoc_insertion_point(class_scope:PostRequests.Operations)
    ))
  ,
  DESCRIPTOR = _POSTREQUESTS,
  __module__ = 'protos.background.main_information_pb2'
  # @@protoc_insertion_point(class_scope:PostRequests)
  ))
_sym_db.RegisterMessage(PostRequests)
_sym_db.RegisterMessage(PostRequests.Operations)


# @@protoc_insertion_point(module_scope)
