# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/redis/redis.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protos/redis/redis.proto',
  package='',
  serialized_pb=_b('\n\x18protos/redis/redis.proto\"=\n\nRedisCache\x12\x1e\n\x04type\x18\x01 \x02(\x0e\x32\x10.RedisCache.Type\"\x0f\n\x04Type\x12\x07\n\x03\x46OO\x10\x01')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_REDISCACHE_TYPE = _descriptor.EnumDescriptor(
  name='Type',
  full_name='RedisCache.Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='FOO', index=0, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=74,
  serialized_end=89,
)
_sym_db.RegisterEnumDescriptor(_REDISCACHE_TYPE)


_REDISCACHE = _descriptor.Descriptor(
  name='RedisCache',
  full_name='RedisCache',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='RedisCache.type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _REDISCACHE_TYPE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=89,
)

_REDISCACHE.fields_by_name['type'].enum_type = _REDISCACHE_TYPE
_REDISCACHE_TYPE.containing_type = _REDISCACHE
DESCRIPTOR.message_types_by_name['RedisCache'] = _REDISCACHE

RedisCache = _reflection.GeneratedProtocolMessageType('RedisCache', (_message.Message,), dict(
  DESCRIPTOR = _REDISCACHE,
  __module__ = 'protos.redis.redis_pb2'
  # @@protoc_insertion_point(class_scope:RedisCache)
  ))
_sym_db.RegisterMessage(RedisCache)


# @@protoc_insertion_point(module_scope)
