#!/bin/sh
find $PWD \( -name "*.py" -o -name "*.proto" \) > cscope.files
cscope -bkq -i cscope.files #-f  is to target perfix e.g. ~/tags/
#ctags -R
ctags -R --c++-kinds=+px --fields=+iaS --extra=+q .
