# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/workorder/daike_struct.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protos/workorder/daike_struct.proto',
  package='',
  serialized_pb=_b('\n#protos/workorder/daike_struct.proto\"\xd1\x03\n\x08\x44\x61ikeApp\x12\r\n\x05\x65vent\x18\x01 \x02(\t\x12 \n\x06ticket\x18\x02 \x02(\x0b\x32\x10.DaikeApp.Ticket\x12\x18\n\x10prev_assignee_id\x18\x03 \x01(\x05\x12\x12\n\ncomment_id\x18\x04 \x01(\x05\x12\x13\n\x0bprev_status\x18\x05 \x01(\t\x1a\xd0\x02\n\x06Ticket\x12\n\n\x02id\x18\x01 \x02(\x05\x12\x0e\n\x06status\x18\x02 \x02(\t\x12\r\n\x05title\x18\x03 \x02(\t\x12\x13\n\x0b\x64\x65scription\x18\x04 \x02(\t\x12\x0c\n\x04tags\x18\x05 \x03(\t\x12\x0f\n\x07user_id\x18\x06 \x02(\t\x12!\n\x03via\x18\x07 \x02(\x0b\x32\x14.DaikeApp.Ticket.Via\x12*\n\x08\x63omments\x18\x08 \x03(\x0b\x32\x18.DaikeApp.Ticket.Comment\x12\x12\n\ncreated_at\x18\t \x02(\t\x12\x12\n\nupdated_at\x18\n \x02(\t\x1a\x16\n\x03Via\x12\x0f\n\x07\x63hannel\x18\x01 \x02(\t\x1aX\n\x07\x43omment\x12\n\n\x02id\x18\x01 \x02(\x05\x12\x0c\n\x04\x62ody\x18\x02 \x02(\t\x12\x0f\n\x07user_id\x18\x03 \x02(\x05\x12\x0e\n\x06public\x18\x04 \x02(\x08\x12\x12\n\ncreated_at\x18\x05 \x02(\t')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_DAIKEAPP_TICKET_VIA = _descriptor.Descriptor(
  name='Via',
  full_name='DaikeApp.Ticket.Via',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='channel', full_name='DaikeApp.Ticket.Via.channel', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=393,
  serialized_end=415,
)

_DAIKEAPP_TICKET_COMMENT = _descriptor.Descriptor(
  name='Comment',
  full_name='DaikeApp.Ticket.Comment',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='DaikeApp.Ticket.Comment.id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='body', full_name='DaikeApp.Ticket.Comment.body', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='user_id', full_name='DaikeApp.Ticket.Comment.user_id', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='public', full_name='DaikeApp.Ticket.Comment.public', index=3,
      number=4, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='created_at', full_name='DaikeApp.Ticket.Comment.created_at', index=4,
      number=5, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=417,
  serialized_end=505,
)

_DAIKEAPP_TICKET = _descriptor.Descriptor(
  name='Ticket',
  full_name='DaikeApp.Ticket',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='DaikeApp.Ticket.id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='status', full_name='DaikeApp.Ticket.status', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='title', full_name='DaikeApp.Ticket.title', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='description', full_name='DaikeApp.Ticket.description', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tags', full_name='DaikeApp.Ticket.tags', index=4,
      number=5, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='user_id', full_name='DaikeApp.Ticket.user_id', index=5,
      number=6, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='via', full_name='DaikeApp.Ticket.via', index=6,
      number=7, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='comments', full_name='DaikeApp.Ticket.comments', index=7,
      number=8, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='created_at', full_name='DaikeApp.Ticket.created_at', index=8,
      number=9, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='updated_at', full_name='DaikeApp.Ticket.updated_at', index=9,
      number=10, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_DAIKEAPP_TICKET_VIA, _DAIKEAPP_TICKET_COMMENT, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=169,
  serialized_end=505,
)

_DAIKEAPP = _descriptor.Descriptor(
  name='DaikeApp',
  full_name='DaikeApp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='event', full_name='DaikeApp.event', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ticket', full_name='DaikeApp.ticket', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='prev_assignee_id', full_name='DaikeApp.prev_assignee_id', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='comment_id', full_name='DaikeApp.comment_id', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='prev_status', full_name='DaikeApp.prev_status', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_DAIKEAPP_TICKET, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=505,
)

_DAIKEAPP_TICKET_VIA.containing_type = _DAIKEAPP_TICKET
_DAIKEAPP_TICKET_COMMENT.containing_type = _DAIKEAPP_TICKET
_DAIKEAPP_TICKET.fields_by_name['via'].message_type = _DAIKEAPP_TICKET_VIA
_DAIKEAPP_TICKET.fields_by_name['comments'].message_type = _DAIKEAPP_TICKET_COMMENT
_DAIKEAPP_TICKET.containing_type = _DAIKEAPP
_DAIKEAPP.fields_by_name['ticket'].message_type = _DAIKEAPP_TICKET
DESCRIPTOR.message_types_by_name['DaikeApp'] = _DAIKEAPP

DaikeApp = _reflection.GeneratedProtocolMessageType('DaikeApp', (_message.Message,), dict(

  Ticket = _reflection.GeneratedProtocolMessageType('Ticket', (_message.Message,), dict(

    Via = _reflection.GeneratedProtocolMessageType('Via', (_message.Message,), dict(
      DESCRIPTOR = _DAIKEAPP_TICKET_VIA,
      __module__ = 'protos.workorder.daike_struct_pb2'
      # @@protoc_insertion_point(class_scope:DaikeApp.Ticket.Via)
      ))
    ,

    Comment = _reflection.GeneratedProtocolMessageType('Comment', (_message.Message,), dict(
      DESCRIPTOR = _DAIKEAPP_TICKET_COMMENT,
      __module__ = 'protos.workorder.daike_struct_pb2'
      # @@protoc_insertion_point(class_scope:DaikeApp.Ticket.Comment)
      ))
    ,
    DESCRIPTOR = _DAIKEAPP_TICKET,
    __module__ = 'protos.workorder.daike_struct_pb2'
    # @@protoc_insertion_point(class_scope:DaikeApp.Ticket)
    ))
  ,
  DESCRIPTOR = _DAIKEAPP,
  __module__ = 'protos.workorder.daike_struct_pb2'
  # @@protoc_insertion_point(class_scope:DaikeApp)
  ))
_sym_db.RegisterMessage(DaikeApp)
_sym_db.RegisterMessage(DaikeApp.Ticket)
_sym_db.RegisterMessage(DaikeApp.Ticket.Via)
_sym_db.RegisterMessage(DaikeApp.Ticket.Comment)


# @@protoc_insertion_point(module_scope)
