---
# Base setup
- hosts: all
  roles: 
    - role: wcl-common

# Perform the Setup of the components
- include: setup.yml
- include: setup-db.yml
- include: setup-docker.yml

# Do the code / app deployment
- include: deploy.yml
