---
- hosts: docker
  tasks:
    - name: ping
      ping: {}
    - name: Start kong container
      docker_container:
        name: kong
        image: kong
        state: started
        restart: true
        ports:
          - "8000:8000"
          - "8443:8443"
          - "8001:8001"
          - "7946:7946"
          - "7946:7946/udp"
        env:
          KONG_DATABASE: postgres
          KONG_PG_HOST: "{{ docker_kong_pg_host }}"
          KONG_PG_PORT: "{{ docker_kong_pg_port }}"
          KONG_PG_USER: "{{ docker_kong_pg_user }}"
          KONG_PG_PASSWORD: "{{ docker_kong_pg_password }}"
          KONG_PG_DATABASE: "{{ docker_kong_pg_database }}"