---
- hosts: postgresql
  roles:
    - role: postgresql
      postgresql_version: 9.5

      postgresql_listen_addresses:
        - 0.0.0.0

      postgresql_databases:
        - name: kong
          owner: kong

      postgresql_users:
        - name: kong
          pass: "{{ db_kong_password }}"

      postgresql_pg_hba_default:
        - type: local
          database: all
          user: '{{ postgresql_admin_user }}'
          address: ''
          method: '{{ postgresql_default_auth_method }}'
          comment: ''
        - { type: local, database: all, user: all, address: '',             method: '{{ postgresql_default_auth_method }}', comment: '"local" is for Unix domain socket connections only' }
        #- { type: host,  database: all, user: all, address: '127.0.0.1/32', method: 'md5', comment: 'IPv4 local connections:' }
        - { type: host,  database: all, user: all, address: '0.0.0.0/0', method: 'md5', comment: 'IPv4 local connections:' }
        - { type: host,  database: all, user: all, address: '::1/128',      method: 'md5', comment: 'IPv6 local connections:' }



