---
# TODO: 16/11/24 improve
- hosts: couchbase
  tasks:
    - name: ping
      ping: {}

- hosts: couchbase
  tasks:
    - name: Create cluster grouping
      group_by: key={{ couchbase_server_node_role }}

#
# Install couchbase on all the nodes
#
- hosts: couchbase
  roles:
    - role: wcl-couchbase
      couchbase_cluster_install: true
      couchbase_server_edition: community
      couchbase_server_centos_ce_url: "{{ couchbase_server_centos_ce_local_url }}"

#
# Init cluster
#
- hosts: couchbase
  roles:
    - role: wcl-couchbase
      couchbase_cluster_init: true
      couchbase_server_node: "{{ hostvars[inventory_hostname]['ansible_' + couchbase_nic].ipv4.address }}"

#
# Add/rebalance cluster
#
- hosts: primary
  roles:
    - role: wcl-couchbase
      couchbase_cluster_add_reblance: true
      couchbase_server_node: "{{ hostvars[inventory_hostname]['ansible_' + couchbase_nic].ipv4.address }}"
      iface: "{{ couchbase_nic }}"