---
- hosts: docker
  roles:
    - role: wcl-docker
      docker_china_mirror: true
      docker_pip_mirror_enable: true
      docker_users:
        - wcladmin
        - ydadmin
        - ylytadmin

  tasks:
    - name: Update dockerfiles
      git:
        repo: https://github.com/wiredcraft-ops/dockerfiles.git
        dest: /opt/wcl/dockerfiles
        version: master
        accept_hostkey: true
        force: true
