Vagrant.configure("2") do |config|

  config.vm.box = "centos/7"
  config.vm.box_check_update = false

  config.ssh.insert_key = false
  config.ssh.private_key_path = '~/.vagrant.d/insecure_private_key'

  config.vm.define 'gateway' do |machine|
    machine.vm.network 'private_network', ip: '192.168.233.10'
    machine.vm.hostname = 'gateway.local'
    machine.vm.provision 'ansible' do |ansible|
      ansible.playbook = 'tests/main.yml'
      ansible.sudo = true
      ansible.inventory_path = 'inventory.vagrant'
      ansible.limit = 'all'
      ansible.host_key_checking = false
    end
  end

end
