---
#
# Setup the base servers
#

- hosts: all
  roles:
    - role: wcl-common
      common_users:
        - name: wcladmin
          sudo: yes
          ssh: yes
          authorized: "{{ wcladmin_ssh_pub_keys }}"
        - name: ydadmin
          sudo: yes
          ssh: yes
          authorized: []
          # authorized: "{{ ydadmin_ssh_pub_keys }}"

      disable_firewall: yes
      handle_firewall: false

    - role: zabbix-agent
      agent_server: "{{ hostvars[groups['zabbix'][0]]['ansible_eth0']['ipv4']['address'] }},zabbix.service.wiredcraft.com,127.0.0.1"
      # Empty both interface and IP to listen to all
      agent_listeninterface:
      agent_listenip: 