# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/base/dbo_settings.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protos/base/dbo_settings.proto',
  package='',
  serialized_pb=_b('\n\x1eprotos/base/dbo_settings.proto\"\x0c\n\nDboSetting')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_DBOSETTING = _descriptor.Descriptor(
  name='DboSetting',
  full_name='DboSetting',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=46,
)

DESCRIPTOR.message_types_by_name['DboSetting'] = _DBOSETTING

DboSetting = _reflection.GeneratedProtocolMessageType('DboSetting', (_message.Message,), dict(
  DESCRIPTOR = _DBOSETTING,
  __module__ = 'protos.base.dbo_settings_pb2'
  # @@protoc_insertion_point(class_scope:DboSetting)
  ))
_sym_db.RegisterMessage(DboSetting)


# @@protoc_insertion_point(module_scope)
