# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/base/user_information.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protos/base/user_information.proto',
  package='',
  serialized_pb=_b('\n\"protos/base/user_information.proto\"\x90\x02\n UserDeliverInformationCollection\x12H\n\x14user_info_collection\x18\x01 \x03(\x0b\x32*.UserDeliverInformationCollection.UserInfo\x1a\xa1\x01\n\x08UserInfo\x12\x0f\n\x07\x61\x64\x64r_id\x18\x01 \x02(\x05\x12\x17\n\x0fis_default_item\x18\x02 \x02(\x08\x12\x0c\n\x04name\x18\x03 \x02(\t\x12\r\n\x05phone\x18\x04 \x02(\t\x12\x0f\n\x07\x63ountry\x18\x05 \x01(\t\x12\x10\n\x08province\x18\x06 \x01(\t\x12\x0c\n\x04\x63ity\x18\x07 \x01(\t\x12\x0c\n\x04\x61rea\x18\x08 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\t \x02(\t')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_USERDELIVERINFORMATIONCOLLECTION_USERINFO = _descriptor.Descriptor(
  name='UserInfo',
  full_name='UserDeliverInformationCollection.UserInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='addr_id', full_name='UserDeliverInformationCollection.UserInfo.addr_id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='is_default_item', full_name='UserDeliverInformationCollection.UserInfo.is_default_item', index=1,
      number=2, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='UserDeliverInformationCollection.UserInfo.name', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='phone', full_name='UserDeliverInformationCollection.UserInfo.phone', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='country', full_name='UserDeliverInformationCollection.UserInfo.country', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='province', full_name='UserDeliverInformationCollection.UserInfo.province', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='city', full_name='UserDeliverInformationCollection.UserInfo.city', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='area', full_name='UserDeliverInformationCollection.UserInfo.area', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='address', full_name='UserDeliverInformationCollection.UserInfo.address', index=8,
      number=9, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=150,
  serialized_end=311,
)

_USERDELIVERINFORMATIONCOLLECTION = _descriptor.Descriptor(
  name='UserDeliverInformationCollection',
  full_name='UserDeliverInformationCollection',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_info_collection', full_name='UserDeliverInformationCollection.user_info_collection', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_USERDELIVERINFORMATIONCOLLECTION_USERINFO, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=39,
  serialized_end=311,
)

_USERDELIVERINFORMATIONCOLLECTION_USERINFO.containing_type = _USERDELIVERINFORMATIONCOLLECTION
_USERDELIVERINFORMATIONCOLLECTION.fields_by_name['user_info_collection'].message_type = _USERDELIVERINFORMATIONCOLLECTION_USERINFO
DESCRIPTOR.message_types_by_name['UserDeliverInformationCollection'] = _USERDELIVERINFORMATIONCOLLECTION

UserDeliverInformationCollection = _reflection.GeneratedProtocolMessageType('UserDeliverInformationCollection', (_message.Message,), dict(

  UserInfo = _reflection.GeneratedProtocolMessageType('UserInfo', (_message.Message,), dict(
    DESCRIPTOR = _USERDELIVERINFORMATIONCOLLECTION_USERINFO,
    __module__ = 'protos.base.user_information_pb2'
    # @@protoc_insertion_point(class_scope:UserDeliverInformationCollection.UserInfo)
    ))
  ,
  DESCRIPTOR = _USERDELIVERINFORMATIONCOLLECTION,
  __module__ = 'protos.base.user_information_pb2'
  # @@protoc_insertion_point(class_scope:UserDeliverInformationCollection)
  ))
_sym_db.RegisterMessage(UserDeliverInformationCollection)
_sym_db.RegisterMessage(UserDeliverInformationCollection.UserInfo)


# @@protoc_insertion_point(module_scope)
