<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Artists' => '艺术家',
  'Bpic Filename' => '大图名',
  'Bpic Url' => '大图路径',
  'Create Time' => '创建时间',
  'Create User' => '创建人',
  'Description' => '说明',
  'ID' => '号码',
  'Name' => '名称',
  'Name Chinese' => '中文名',
  'Name Pinyin' => '名称拼音',
  'Publish Time' => '出版时间',
  'Spic Filename' => '小图名',
  'Spic Url' => '小图路径',
  'Status' => '状态',
  'Update Time' => '更新时间',
  'Update User' => '更新人',
  'Add Albumn' => '添加唱片',
  'Albumn' => '唱片集',
  'Are you sure to delete albumn' => '确定要删除唱片吗',
  'Are you sure to delete albumn {name}?' => '确定要删除该唱片{name}吗？',
  'Are you sure to delete all albumns?' => '确定要删除所有唱片吗？',
  'Are you sure to delete this albumn?' => '确定要删除该唱片吗？',
  'Create Albumn' => '创建唱片',
  'Delete this albumn' => '删除该唱片',
  'Fields with {required} are required to {operate} albumn.' => '标记 {required} 的项目必须输入，以便{operate}唱片。',
  'Update Albumn' => '更新唱片集',
  'Update this albumn' => '更新该唱片',
  'View this albumn' => '查看该唱片',
  'albumn' => '唱片集',
);
