<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Add Application' => '添加应用',
  'Application' => '应用',
  'Are you sure to delete all applications?' => '你确定要删除所有应用吗？',
  'Are you sure to delete application' => '你确定要删除应用吗',
  'Are you sure to delete application {name}?' => '你确定要删除应用{name}吗？',
  'Are you sure to delete this application?' => '你确定要删除这个应用吗',
  'Create Application' => '创建应用',
  'Delete this application' => '删除该应用',
  'Fields with {required} are required to {operate} application.' => '标记 {required} 的项目必须输入，以便{operate}应用。',
  'Update Application' => '更新应用',
  'Update this application' => '更新该应用',
  'View this application' => '查看该应用',
  'application' => '应用',
);
