<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Birthday' => '生日',
  'Bpic Filename' => '图片',
  'Bpic Url' => '图片链接',
  'Country' => '国籍',
  'Create Time' => '创建时间',
  'Create User' => '创建人',
  'Description' => '说明',
  'ID' => '序号',
  'Name' => '名字',
  'Name Chinese' => '中文名',
  'Name Count' => '名字笔画数',
  'Name Pinyin' => '名字拼音',
  'Periods' => '时期',
  'Products' => '产品',
  'Spic Filename' => '小图名',
  'Spic Url' => '小图路径',
  'Status' => '状态',
  'Update Time' => '更新时间',
  'Update User' => '更新人',
  'Add Artist' => '添加艺术家',
  'Are you sure to delete all artists?' => '你确定要删除所有艺术家吗？',
  'Are you sure to delete artist' => '你确定要删除艺术家',
  'Are you sure to delete artist {name}?' => '你确定要删除艺术家{name}吗？',
  'Are you sure to delete this artist?' => '你确定要删除该艺术家吗？',
  'Artist' => '艺术家',
  'Create Artist' => '创建艺术家',
  'Delete this artist' => '删除该艺术家',
  'Fields with {required} are required to {operate} artist.' => '标记 {required} 的项目必须输入，以便{operate}艺术家。',
  'Update Artist' => '更新艺术家',
  'Update this artist' => '更新该艺术家',
  'View this artist' => '查看艺术家',
  'artist' => '艺术家',
  'Category Confirm Window' => '艺术家分类设置',
  'Are you sure to add artist ' => '确认要给艺术家 ',
  'Notice: artist can add to multi-category.' => '提示：艺术家可以加入到多个分类中',
  'to a category?' => '设置分类吗？',
  '{name} is a member of {category} yet.' => '{name} 已经是分类 {category} 的成员。',
  '{name} added to category {category} successfully.' => '{name} 已经成功加入到分类 {category} 中。',
  'Parameter Error！' => '参数错误！',
  'Add this artist to category' => '将歌手加入到歌手分类',
  'Check Artist Picture' => '检查图片',
);
