<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Bpic Filename' => '图片',
  'Bpic Url' => '图片链接',
  'Create Time' => '创建时间',
  'Create User' => '创建人',
  'Description' => '说明',
  'ID' => '序号',
  'Name' => '名称',
  'Spic Filename' => '小图',
  'Spic Url' => '小图链接',
  'Status' => '状态',
  'Update Time' => '更新时间',
  'Update User' => '更新人',
  'Add Category' => '添加分类',
  'Are you sure to delete all categories?' => '你确定要删除所有分类吗？',
  'Are you sure to delete category' => '你确定要删除分类吗',
  'Are you sure to delete category {name}?' => '你确定要删除分类{name}吗？',
  'Are you sure to delete this category?' => '你确定要删除该分类吗？',
  'Category' => '分类',
  'Create Category' => '创建分类',
  'Delete this category' => '删除该分类',
  'Fields with {required} are required to {operate} category.' => '标记 {required} 的项目必须输入，以便{operate}分类。',
  'Update Category' => '更新分类',
  'Update this category' => '更新此分类',
  'View this category' => '查看分类',
  'category' => '分类',
);
