<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Code' => '二维码',
  'Create Time' => '创建时间',
  'Create User' => '创建用户',
  'Expire' => '到期',
  'ID' => '序号',
  'Room' => '包房',
  'Start Time' => '开始时间',
  'Update Time' => '更新时间',
  'Update User' => '更新用户',
  'Add CheckinState' => '增加登记状态',
  'Are you sure to delete all checkin states?' => '您确定要删除所有登记状态？',
  'Are you sure to delete checkinstate' => '您确定要删除登记状态？',
  'Are you sure to delete checkinstate {name}?' => '您确定要删除登记状态｛name｝',
  'Are you sure to delete this checkinstate?' => '您确定要删除此条登记状态',
  'CheckinState' => '登记状态',
  'Create CheckinState' => '新建登记状态',
  'Delete this checkinstate' => '删除此条登记状态',
  'Fields with {required} are required to {operate} checkinstate.' => '标记 {required} 的项目必须输入，以便{operate}登记状态。',
  'Update CheckinState' => '更新登记状态',
  'Update this checkinstate' => '更新此条登记状态',
  'View this checkinstate' => '查看此条登记状态',
  'checkinstate' => '登记状态',
);
