<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Checkin Time' => '登记时间',
  'Create Time' => '创建时间',
  'Create User' => '创建人',
  'ID' => '序号',
  'Room' => '包房',
  'Uid' => '更新序号',
  'Update Time' => '更新时间',
  'Update User' => '更新人',
  'Are you sure to delete all checkin users?' => '你确定删除所有登录用户吗？',
  'Are you sure to delete checkinuser' => '你确定要删除登录用户吗',
  'Are you sure to delete checkinuser {name}?' => '你确定要删除登录用户{name}吗？',
  'Are you sure to delete this checkinuser?' => '你确定要删除该登录用户吗？',
  'CheckinUser' => '登录用户',
  'Create CheckinUser' => '创建登录用户',
  'Delete this checkinuser' => '删除该登录用户',
  'Fields with {required} are required to {operate} checkinuser.' => '标记 {required} 的项目必须输入，以便{operate}登录用户。',
  'Update CheckinUser' => '更新登录用户',
  'Update this checkinuser' => '更新此登录用户',
  'View this checkinuser' => '查看此登录用户',
  'checkinuser' => '登录用户',
);
