<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Code' => '二维码',
  'Create Time' => '创建时间',
  'Create User' => '创建用户',
  'Description' => '描述',
  'Duration' => '持续期',
  'Expire' => '到期',
  'ID' => '序号',
  'Name' => '名称',
  'Room' => '包房',
  'Update Time' => '更新时间',
  'Update User' => '更新用户',
  'Are you sure to delete all checkin codes?' => '您确定要删除所有二维码',
  'Are you sure to delete checkincode' => '您确定要删除二维码',
  'Are you sure to delete checkincode {name}?' => '您确定要删除二维码｛name｝',
  'Are you sure to delete this checkincode?' => '您确定要删除此条二维码',
  'CheckinCode' => '二维码',
  'Create CheckinCode' => '创建二维码',
  'Delete this checkincode' => '删除此条二维码',
  'Fields with {required} are required to {operate} checkincode.' => '标记 {required} 的项目必须输入，以便{operate}二维码。',
  'Update CheckinCode' => '更新二维码',
  'Update this checkincode' => '更新此条二维码',
  'View this checkincode' => '查看此条二维码',
  'checkincode' => '二维码',
);
