<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Create Time' => '创建时间',
  'Create User' => '创建人',
  'Device' => '设备',
  'ID' => '序号',
  'Index Num' => '索引号',
  'Media' => '媒体',
  'Play Posttime' => '提交时间',
  'Play Status' => '播放状态',
  'Play Timestamp' => '播放时间标记',
  'Status' => '状态',
  'Update Time' => '更新时间',
  'Update User' => '更新人',
  'Add DevicePlaylist' => '添加设备播放列表',
  'Are you sure to delete all device playlists?' => '你确定要删除所有设备播放列表吗',
  'Are you sure to delete deviceplaylist' => '你确定要删除设备播放列表吗',
  'Are you sure to delete deviceplaylist {name}?' => '你确定要删除设备播放列表{name}吗？',
  'Are you sure to delete this deviceplaylist?' => '你确定要删除此设备播放列表吗',
  'Create DevicePlaylist' => '创建设备播放列表',
  'Delete this deviceplaylist' => '删除此设备播放列表',
  'DevicePlaylist' => '设备播放列表',
  'Fields with {required} are required to {operate} deviceplaylist.' => '标记 {required} 的项目必须输入，以便{operate}设备播放列表。 ',
  'Update DevicePlaylist' => '更新设备播放列表',
  'Update this deviceplaylist' => '更新此设备播放列表',
  'View this deviceplaylist' => '查看此设备播放列表',
  'deviceplaylist' => '设备播放列表',
);
