<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Create Time' => '创建时间',
  'Create User' => '创建者',
  'Device' => '设备',
  'ID' => '序号',
  'Room' => '包房',
  'Status' => '状态',
  'Update Time' => '更新时间',
  'Update User' => '更新人',
  'Add DeviceState' => '添加设备状态',
  'Are you sure to delete all device states?' => '你确定要删除所有设备状态吗？',
  'Are you sure to delete devicestate' => '你确定要删除设备状态吗',
  'Are you sure to delete devicestate {name}?' => '你确定要删除设备状态{name}吗？',
  'Are you sure to delete this devicestate?' => '你确定要删除此设备状态吗？',
  'Create DeviceState' => '创建设备状态',
  'Delete this devicestate' => '删除此设备状态',
  'DeviceState' => '设备状态',
  'Fields with {required} are required to {operate} devicestate.' => '标记 {required} 的项目必须输入，以便{operate}设备状态。 ',
  'Update DeviceState' => '更新设备状态',
  'Update this devicestate' => '更新此设备状态',
  'View this devicestate' => '查看此设备状态',
  'devicestate' => '设备状态',
);
