<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Create Time' => '创建时间',
  'Create User' => '创建人',
  'Description' => '',
  'ID' => '序号',
  'Imei' => '序列号',
  'Ip' => '网址',
  'Name' => '名称',
  'Status' => '状态',
  'Type' => '类型',
  'Update Time' => '更新时间',
  'Update User' => '更新人',
  'Add Device' => '添加设备',
  'Are you sure to bind device' => '你确定要绑定设备吗',
  'Are you sure to bind this device?' => '你确定要绑定这一设备吗',
  'Are you sure to delete all devices?' => '你确定要删除所有设备吗',
  'Are you sure to delete device' => '你确定要删除设备吗',
  'Are you sure to delete device {name}?' => '你确定要删除设备{name}吗？',
  'Are you sure to delete this device?' => '你确定要删除这一设备吗',
  'Are you sure to unbind device' => '你确定要解除绑定设备吗',
  'Create Device' => '创建设备',
  'Delete this device' => '删除这一设备',
  'Device' => '设备',
  'Fields with {required} are required to {operate} device.' => '标记 {required} 的项目必须输入，以便{operate}设备。',
  'Update Device' => '更新设备',
  'Update this device' => '更新该设备',
  'View this device' => '查看该设备',
  'bind this device to room' => '在包房中绑定这一设备',
  'device' => '设备',
  'unbind this device to any room' => '任何包房都不绑定这一设备',
);
