<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Albumn' => '唱片',
  'Artist' => '艺术家',
  'Artist ID' => '艺术家ID',
  'Artist Name' => '艺术家名',
  'Audio Count' => '音频数',
  'Audio Filename' => '音频文件名',
  'Audio Filename1' => '音频文件名1',
  'Audio Filename2' => '音频文件名2',
  'Audio Url' => '音频路径',
  'Audio Url1' => '音频路径1',
  'Audio Url2' => '音频路径2',
  'Audio Volume1' => '音频音量1',
  'Audio Volume2' => '音频音量2',
  'Bpic Filename' => '大图',
  'Bpic Url' => '大图链接',
  'Category' => '分类',
  'Create Time' => '创建时间',
  'Create User' => '创建者',
  'Description' => '说明',
  'Duration' => '时长',
  'Hot Grade' => '热度',
  'ID' => '序号',
  'Is New' => '新歌',
  'Led Tag' => 'LED 名称',
  'Light Tag' => '灯光名称',
  'Lyrics' => '歌词',
  'Lyrics Chinese' => '中文歌词',
  'Lyrics Pinyin' => '歌词拼音',
  'Name' => '歌名',
  'Name Chinese' => '歌名中文名',
  'Name Count' => '歌名笔画数',
  'Name Pinyin' => '歌名拼音',
  'Origin Audio' => '源音频',
  'Play Count' => '播放数',
  'Qc Grade' => '',
  'Song Lang' => '歌曲语言',
  'Song Style' => '歌曲风格',
  'Songid' => '歌曲序号',
  'Spic Filename' => '小图',
  'Spic Url' => '小图链接',
  'Status' => '状态',
  'Update Time' => '更新时间',
  'Update User' => '更新人',
  'Video Codec' => '视频号',
  'Video Comment' => '视频评论',
  'Video Dir Name' => '视频目录',
  'Video Filename' => '视频文件名',
  'Video Real Url' => '视频真实路径',
  'Video Res' => '视频分辨率',
  'Video Style' => '视频风格',
  'Video Url' => '视频路径',
  'Video Version' => '视频版本',
  'Add Media' => '添加媒体',
  'Are you sure to delete all medias?' => '确定要删除所有媒体吗？',
  'Are you sure to delete media' => '你确定要删除媒体',
  'Are you sure to delete media {name}?' => '你确定要删除媒体{name}吗？',
  'Are you sure to delete this media?' => '你确定要删除此媒体吗？',
  'Create Media' => '创建媒体',
  'Delete this media' => '删除此媒体',
  'Fields with {required} are required to {operate} media.' => '标记 {required} 的项目必须输入，以便{operate}媒体。',
  'Media' => '媒体',
  'Update Media' => '更新媒体',
  'Update this media' => '更新此媒体',
  'View this media' => '查看此媒体',
  'media' => '媒体',
  'Chart Confirm Window' => '热歌榜设置确定',
  'Are you sure to add song ' => '确认要将媒体 ',
  'Notice: songs can add to multi-chart.' => '提示：媒体文件可以加入到多个热歌榜中',
  'to a chart?' => ' 到热歌榜？',
  '{name} is a member of {category} yet.' => '{name} 已经是分类 {category} 的成员。',
  '{name} added to chart {category} successfully.' => '{name} 已经成功加入到分类 {category} 中。',
  'Parameter Error！' => '参数错误！',
  'Add this media to category' => '将歌曲加入到热歌榜',
);
