<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Are you sure to delete platformuser {name}?' => '你确定要删除平台使用者{name}吗？',
  'Are you sure to delete platformuser {name} ' => '你确定要删除平台使用者{name}吗',
  'Auth Type' => '用户类型',
  'Avatar Url' => '头像链接',
  'Create Time' => '创建时间',
  'Create User' => '创建者',
  'Display Name' => '显示名称',
  'Email' => '邮件',
  'ID' => '序号',
  'Last Login Time' => '上一次登录时间',
  'Mobile' => '手机',
  'Openid' => '打开序号',
  'Password' => '密码',
  'Profile Data' => '概况',
  'Role' => '角色',
  'Token' => '标记',
  'Type' => '方式',
  'Update Time' => '更新时间',
  'Update User' => '更新者',
  'Username' => '使用者',
  'Add PlatformUser' => '添加平台用户',
  'Are you sure to delete all platform users?' => '你确定要删除所有平台用户吗',
  'Are you sure to delete platformuser' => '你确定要删除平台用户吗',
  'Are you sure to delete platformuser {name} ' => '你确定要删除平台用户{name}吗',
  'Are you sure to delete this platformuser?' => '你确定要删除此平台用户吗？',
  'Create PlatformUser' => '创建平台用户',
  'Delete this platformuser' => '删除此平台用户',
  'Fields with {required} are required to {operate} platformuser.' => '标记 {required} 的项目必须输入，以便{operate}平台用户。 ',
  'PlatformUser' => '平台用户',
  'Update PlatformUser' => '更新平台用户',
  'Update this platformuser' => '更新此平台用户',
  'View this platformuser' => '查看此平台用户',
  'platformuser' => '平台用户',
);
