<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Bigpic Filename' => '大图片文件名',
  'Bigpic Url' => '大图片路径',
  'Content' => '目录',
  'Create Time' => '创建时间',
  'Create User' => '创建者',
  'Description' => '说明',
  'ID' => '序号',
  'Large Room' => '大包房',
  'Medium Room' => '中包房',
  'Name' => '名称',
  'Normal Room' => '普通包',
  'Price/Hour' => '价格/小时',
  'Room Type' => '包房规格',
  'Roomid' => '包房序号',
  'Smallpic Filename' => '小图片文件名',
  'Smallpic Url' => '小图片路径',
  'Status' => '状态',
  'Update Time' => '更新时间',
  'Update User' => '更新者',
  'Vendor' => '供应商',
  'Add Room' => '添加包房',
  'Are you sure to delete all rooms?' => '你确定要删除所有包房吗？',
  'Are you sure to delete room' => '你确定要删除包房吗？',
  'Are you sure to delete room {name}?' => '你确定要删除包房{name}吗？',
  'Are you sure to delete this room?' => '你确定要删除此包房吗？',
  'Are you sure to open room' => '你确定要开包房吗',
  'Are you sure to open this room?' => '你确定要开此包房吗？',
  'Are you sure to reset room' => '你确定要重置包房吗',
  'Are you sure to reset this room?' => '你确定要重置此包房吗？',
  'Create Room' => '创建包房',
  'Delete this room' => '删除此包房',
  'Fields with {required} are required to {operate} room.' => '标记 {required} 的项目必须输入，以便{operate}包房。 ',
  'Notice: open room will reset all records of this room, <br>and will create a new check in QR code for new customers to check in.' => '注意：打开包房将会重置此包房的所有记录，<br>而且将会为了新顾客登记而创建一个新的二维码',
  'Notice: reset in will clear all records of this room, <br>customers can not check in anymore.' => '注意：重置将会清空此房间的所有记录，<br>顾客将不能再登记',
  'Open this room' => '打开此包房',
  'Reset this room' => '重置此包房',
  'Room' => '包房',
  'Update Room' => '更新包房',
  'Update this room' => '更新此包房',
  'View this room' => '查看此包房',
  'room' => '包房',
);
