<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Booking Time' => '预订时间',
  //'Canceled' => '取消',
  //'Complete' => '完成',
  'Create Time' => '创建时间',
  'Create User' => '创建者',
  'Description' => '说明',
  'Duration' => '预定时长',
  'Expire' => '有效期',
  //'Expired' => '过期',
  'ID' => '名称',
  'Order Amount' => '订购金额',
  'Order Code' => '订购编码',
  'Order Invoice' => '发票编码',
  'Order Time' => '订购时间',
  'Payed by Alipay' => '支付宝支付',
  'Payed by Cash' => '现金支付',
  'Payed by Wechat' => '微信支付',
  //'Pending' => '待定',
  'Room' => '包房',
  'Room Status' => '包房状态',
  'Update Time' => '更新时间',
  'Update User' => '更新者',
  'User' => '使用者',
  'Waiting Cash' => '等待付现',
  'unknown' => '未知',
  'Add RoomBooking' => '添加包房预订',
  'Advanced Search' => '高级搜索',
  'Are you sure to delete all room bookings?' => '你确定要删除所有包房预订吗？',
  'Are you sure to delete roombooking' => '你确定要删除包房预订',
  'Are you sure to delete roombooking {name}?' => '你确定要删除包房预订{name}？',
  'Are you sure to delete this roombooking?' => '你确定要删除此包房预订吗？',
  'Create RoomBooking' => '创建包房预订',
  'Delete All room bookings Confirm Window' => '删除所有包房预订确认窗口',
  'Delete roombooking Confirm Window' => '删除包房预订确认窗口',
  'Delete this roombooking' => '删除此包房预订',
  'Fields with {required} are required to {operate} roombooking.' => '标记 {required} 的项目必须输入，以便{operate}包房预订。',
  'RoomBooking' => '包房预订',
  'Update RoomBooking' => '更新包房预订',
  'Update this roombooking' => '更新此包房预订',
  'View this roombooking' => '查看此包房预订',
  'roombooking' => '包房预订',
);
