<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Add RoomExtra' => '添加包房附加费用',
  'Advanced Search' => '高级搜索',
  'Are you sure to delete all room extras?' => '你确定要删除所有包房附加费用？',
  'Are you sure to delete roomextra' => '你确定要删除包房附加费用',
  'Are you sure to delete roomextra {name}?' => '你确定要删除包房附加费用{name}',
  'Are you sure to delete this roomextra?' => '你确定要删除此包房附加费用',
  'Create RoomExtra' => '创建包房附加费用',
  'Delete All room extras Confirm Window' => '删除所有包房附加费用确认窗口',
  'Delete roomextra Confirm Window' => '删除包房附加费用确认窗口',
  'Delete this roomextra' => '删除此包房附加费用',
  'Fields with {required} are required to {operate} roomextra.' => '标记 {required} 的项目必须输入，以便{operate}包房附加费用。',
  'RoomExtra' => '包房附加费用',
  'Update RoomExtra' => '更新包房附加费用',
  'Update this roomextra' => '更新此包房附加费用',
  'View this roomextra' => '查看此包房附加费用',
  'roomextra' => '包房附加费用',
);
