<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'API Call Failed!' => '接口调用失败',
  'ID' => '',
  'API Settings' => '接口设置',
  'Create' => '创建',
  'Create Category Root' => '创建分类根节点',
  'Fields with {required} are required to {operate} setting.' => '标记 {required} 的项目必须输入，以便{operate}设置。',
  'Refresh Token' => '刷新API Token',
  'Register User' => '注册API用户',
  'Reset' => '重置输入',
  'Save Changes' => '保存更改',
  'Setting' => '接口',
  'Settings' => '接口设置',
  'Update' => '更改设置',
  'Update this setting' => '更改设置项目',
  'View this setting' => '查看设置项目',
  'create' => '创建',
  'update' => '更改',
  ' updated successfully.' => ' 更新成功',
  'API error!' => '接口错误！',
  'Content' => '设置内容',
  'Create Time' => '创建时间',
  'Create User' => '创建人',
  'Name' => '设置名称',
  'Please register API user first!' => '请首先注册API用户！',
  'Result decode error!' => '结果解码错误！',
  'The requested page does not exist.' => '请求的信息不存在！',
  'The requested setting can not be edit now.' => '系统设置暂时不能修改！',
  'Update Time' => '更新时间',
  'Update User' => '更新人',
  'Calltime' => '调用时间',
  'Call Api' => '调用接口',
  'Call ID' => '用户 ID',
  'Call Ip' => 'IP',
  'Call Type' => '调用类型',
  'Call Count' => '统计次数',
);
