<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Add Version' => '添加版本',
  'Are you sure to delete all versions?' => '你确定要删除所有版本吗',
  'Are you sure to delete this version?' => '你确定要删除此版本吗',
  'Are you sure to delete version' => '你确定要删除版本吗',
  'Are you sure to delete version {name}?' => '你确定要删除版本{name}吗',
  'Create Version' => '创建版本',
  'Delete this version' => '删除此版本',
  'Fields with {required} are required to {operate} version.' => '标记 {required} 的项目必须输入，以便{operate}版本。',
  'Update Version' => '更新版本',
  'Update this version' => '更新此版本',
  'Version' => '版本',
  'View this version' => '查看此版本',
  'version' => '版本',
  'push sent failed!' => '升级推送信息发布失败！',
  'push sent successful!' => '升级推送信息发布成功！',
);
